// <auto-generated />
using System;
using DrPrint.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrPrint.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220816124201_CategoryFlags")]
    partial class CategoryFlags
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DrPrint.Shared.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyVat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DrPrint.Shared.CartItem", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DrPrint.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Description = "Personalizam o gama larga de produse pe care le puteti folosi pentru cadouri, decor sau promotionale pentru afacerea Dvs: Tricouri, Cani, Halbe de Bere, Suporturi Pahare, Fotografii Digitale, Tablouri pe Panza (Canvas), Briechete, Brelocuri, Pixuri, Ceasuri de Perete, CD-uri, DVD-uri si Carcase Printate, Jucarii, Magneti de frigider, Medalioane, Mouse-paduri, Placute Ceramice pentru Ocazii sau Comemorative, Puzzle, Perne si multe alte produse la cerere. Gasiti fiecare produs postat in interiorul siteului cu toate informatiile necesare.",
                            Name = "Articole Personalizate",
                            Url = "articole-personalizate",
                            Visible = true
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Description = "Imprimam documente, carti de vizita, pliante, flyere, postere, foto, canvas si multe altele la cerere. Imprimam formate de la A4 la formate mari A0. Printarea se realizeaza pe utilaje Konica Minolta si Canon. Realizam fonte exceptionale. Comanda on-line sau in centrul de printare.",
                            Name = "Print digital",
                            Url = "print-digital",
                            Visible = true
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Description = "",
                            Name = "Fotografii Si Rame Foto",
                            Url = "fotografii-si-rame-foto",
                            Visible = true
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Description = "Drprint.ro va ofera o gama larga de solutii de publicitate. Va oferim: Bannere, Autocolante printate sau taiate la cutter-ploter pentru decorarea vitrinelor sau insctiptionari auto, Sisteme de afisaj: People stopper, Rame Aluminiu Click, sisteme Roll-up, Casete luminoase. Totul pentru afacerea Dvs. Pentru orice informatii suplimentare nu ezitati sa ne contactati!",
                            Name = "Productie Publicitara",
                            Url = "productie-publicitara",
                            Visible = true
                        });
                });

            modelBuilder.Entity("DrPrint.Shared.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DrPrint.Shared.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DrPrint.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OriginalPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Carti de vizita color fata-verso print carton special super-glossy. Realizam fonte excelente. Pentru a veni in sprijinul Dvs. in Bucuresti livrarea este gratuita! Tel/WhatsApp 0723896370. E-mail: contact@drprint.ro",
                            Featured = true,
                            ImageUrl = "/images/products/27255-scaled-800x800-min.jpg",
                            Name = "Carti de vizita fata-verso",
                            OriginalPrice = 0.80000000000000004,
                            Price = 0.80000000000000004,
                            Stock = 100,
                            SubCategoryId = 28,
                            View = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Carti de vizita color o fata print, carton special ultra glossy. Realizam fonte excelente. Putem adauga gratuit cod QR. Pentru a veni in sprijinul Dvs. in Bucuresti livrarea este gratuita! Tel/WhatsApp 0723896370. E-mail: contact@drprint.ro",
                            Featured = false,
                            ImageUrl = "/images/products/buisness-card-800x800-min.jpg",
                            Name = "Carti de vizita o fata",
                            OriginalPrice = 0.5,
                            Price = 0.5,
                            Stock = 100,
                            SubCategoryId = 28,
                            View = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Etichete autoadezive A4 dreptunghiulare, 52.5 x 29.7 mm. Sunt etichete in coala, coli autocolante A4 cu finisare mata pentru imprimarea etichetelor de produs, a codurilor de bare, sau a altor informatii necesare identificarii si gestionarii produselor.",
                            Featured = true,
                            ImageUrl = "/images/products/etichete-autoadezive-800x800-min.jpg",
                            Name = "Coli autoadezive A4, printate",
                            OriginalPrice = 5.0,
                            Price = 5.0,
                            Stock = 100,
                            SubCategoryId = 29,
                            View = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Etichete autoadezive 24/A4 dreptunghiulare. Sunt etichete in coala, coli autocolante A4 cu finisare mata pentru imprimarea etichetelor de produs, a codurilor de bare, sau a altor informatii necesare identificarii si gestionarii produselor.",
                            Featured = false,
                            ImageUrl = "/images/products/etichete-autoadezive-800x800-min.jpg",
                            Name = "Etichete autoadezive 24/A4 Business",
                            OriginalPrice = 0.29999999999999999,
                            Price = 0.29999999999999999,
                            Stock = 100,
                            SubCategoryId = 29,
                            View = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Etichete autoadezive 65/A4 dreptunghiulare. Sunt etichete in coala, coli autocolante A4 cu finisare mata pentru imprimarea etichetelor de produs, a codurilor de bare, sau a altor informatii necesare identificarii si gestionarii produselor.",
                            Featured = false,
                            ImageUrl = "/images/products/etichete-autoadezive-800x800-min.jpg",
                            Name = "Etichete autoadezive 65/A4",
                            OriginalPrice = 0.20000000000000001,
                            Price = 0.20000000000000001,
                            Stock = 100,
                            SubCategoryId = 29,
                            View = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Etichete autoadezive A5 dreptunghiulare. Sunt etichete in coala, coli autocolante A4 cu finisare mata pentru imprimarea etichetelor de produs, a codurilor de bare, sau a altor informatii necesare identificarii si gestionarii produselor.",
                            Featured = true,
                            ImageUrl = "/images/products/etichete-autoadezive-800x800-min.jpg",
                            Name = "Etichete autoadezive A5",
                            OriginalPrice = 2.5,
                            Price = 2.5,
                            Stock = 100,
                            SubCategoryId = 29,
                            View = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "De culoare neagra, canile magice se personalizeaza cu poza favorita care nu este vizibila atunci cand cana este rece. Dupa ce se toarna un lichid fierbinte (ceai, cafea, etc), aceasta devine alba permitand vizualizarea fotografiei si creand o surpriza placuta.",
                            Featured = false,
                            ImageUrl = "/images/products/c870x524-800x800-min.jpg",
                            Name = "Cana 'Magica' personalizata cu poza si textul favorit",
                            OriginalPrice = 45.0,
                            Price = 40.0,
                            Stock = 100,
                            SubCategoryId = 4,
                            View = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Fa un cadou minunat sau decor pentru amintirile tale foto. Rama foto cu 6 poze. Pozele personalizate sunt incluse in pret. Dimensiune: 48 x 36 cm",
                            Featured = true,
                            ImageUrl = "/images/products/youandi-frame.jpg",
                            Name = "Rama foto colaj bleu YOU & ME cu 6 poze personalizate",
                            OriginalPrice = 79.0,
                            Price = 70.0,
                            Stock = 100,
                            SubCategoryId = 39,
                            View = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "People Stopper/Panou pietonal, confectionat din aluminiu anodizat cu colturi taiate la 45grade, profile clip-clap, folie transparenta reflectorizanta.",
                            Featured = false,
                            ImageUrl = "/images/products/A-board_people_stopper-1-1-800x800-min.png",
                            Name = "People Stopper 50x70 cm",
                            OriginalPrice = 490.0,
                            Price = 450.0,
                            Stock = 10,
                            SubCategoryId = 41,
                            View = 0
                        });
                });

            modelBuilder.Entity("DrPrint.Shared.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Intra in aceasta categorie si alege din zeci de produse personalizate la pret redus. Trimiteti comanda, pozele pt personalizare si datele de livrare pe: contact@drprint.ro sau WhatsApp: 0723896370. In Bucuresti livrarea este gratuita iar in tara prin posta Romana 13 lei sau curier prioripost, 20 lei.",
                            ImageUrl = "/images/subcategory/articole-personalizate/reduceri.jpg",
                            Name = "Cadouri Personalizate - REDUCERI % -",
                            Url = "reduceri-cadouri-personalizate"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Cadouri unice, personalizate pentru copiii Dvs. pe care le vor pretui toată viata. Alegeti dintr-o gama larga de produse: jucarii de plus, cani, tricouri, puzzle-uri, perne, globuri foto, ghiozdane, penare si multe alte cadouri. Bucuria copilului Dvs. va fi nepretuita!",
                            ImageUrl = "/images/subcategory/articole-personalizate/ziua-copilului-idei-cadouri.jpg",
                            Name = "Ziua Copilului - Idei Cadouri Personalizate",
                            Url = "ziua-copilului-idei-cadouri"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Canile cu insertie foto personalizate prin introducerea unei fotografii in suportul de plastic transparent care inconjoara cana sunt indeale pentru a va transporta cafeaua in drum inspre serviciu sau in masina, la picnic etc fiind izolate cu capac evitand riscul de a varsa continutul. Acestea au si proprietati de termos pastrand calda bautura Dvs. un timp indelungat. Puteti personaliza si bidoane de plastic pentru copilul Dvs. Alegeti din modelele prezentate in continuare.  ",
                            ImageUrl = "/images/subcategory/articole-personalizate/cani-cu-insertie-foto.jpg",
                            Name = "Cani Cu Insertie Foto",
                            Url = "cani-cu-insertie-foto"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Personalizam cani din ceramica superioara cu poza sau textul Dvs.. Puteti face cadouri sau va puteti promova compania prin cani personalizate cu logoul si mesajul Dvs.. Puteti alege dintr-o gama variata de cani: albe, cu tortita si interiorul color, cani magice termosensibile, cani cu tortita in forma de inima, cani aurii sau argintii, sidefate, cani expresso cu farfurioare, cani termos cu insertie foto.",
                            ImageUrl = "/images/subcategory/articole-personalizate/cani-personalizate.jpg",
                            Name = "Cani Personalizate",
                            Url = "cani-personalizate"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Personalizam cani pentru sarbatori din ceramica superioara cu poza sau textul Dvs..",
                            ImageUrl = "/images/subcategory/articole-personalizate/cani-pentru-sarbatori.jpg",
                            Name = "Cani Personalizate Pentru Sarbatori",
                            Url = "cani-personalizate-pentru-sarbatori"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Creati perne personalizate pentru cadouri deosebite, restaurant, banquette, zona de relaxare in aer liber sau sufrageria Dvs. Suntem foarte mandri de detaliu si calitatea tuturor pernelor personalizate pe care le facem. Puteti alege perne satinate, diferite culori sau albe/argintii, perne patrate, inima, perne cuplu. De asemenea va oferim perne personalizate cu diferite mesaje si haioase pentru jumatatea ta. Alegeti din multutudine de modele prezentate in aceasta categorie.",
                            ImageUrl = "/images/subcategory/articole-personalizate/perne-personalizate.jpg",
                            Name = "Perne Personalizate",
                            Url = "perne-personalizate"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Personalizam tricouri pentru cadouri, pentru angajatii firmei Dvs. sau ca materiale promotionale si campanii fiind un mod eficient de a face publicitate. Personalizam tricouri pentru barbati, femei si copii. Tricourile pot fii din bumbac 100% sau polyester ideale pentru activitati sportive. Personalizarile se realizeaza prin termotransfer sau serigrafie pentru cantitati mari.",
                            ImageUrl = "/images/subcategory/articole-personalizate/tricouri-personalizate.jpg",
                            Name = "Tricouri Personalizate",
                            Url = "tricouri-personalizate"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Personalizate cu pozele preferate, globurile foto reprezinta un decor minunat pentru biroul Dvs sau pentru pomul de Craciun. Puteti faceun cadou deosebit pentru Craciun, Ziua Indragostitilor zile onomastice, sau orice alta ocazie deosebita.",
                            ImageUrl = "/images/subcategory/articole-personalizate/globuri-foto.jpg",
                            Name = "Globuri Foto Personalizate",
                            Url = "globuri-foto-personalizate"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Magnetii de frigider personalizati pot fii folositi ca invitatii de nunta si botez, marturii, cadouri deosebite, carti de vizita sau o modalitate excelenta de reclama pentru afacerea Dvs. Puteti opta pentru: magneti printati pe hartie foto pentru o claritate si vivacitate ridicata a culorilor si suport folie magnetica flexibila, magneti flexibili cu insertie foto in diferite forme, magneti rigizi din platic cu insertie foto.",
                            ImageUrl = "/images/subcategory/articole-personalizate/magneti-personalizati.jpg",
                            Name = "Magneti De Frigider Personalizati",
                            Url = "magenti-de-frigider-personalizati"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Personalizam cesuri din plastic,  sticla, MDF (lemn) sau Mahon - un cadou deosebit  sau un accesoriu util pentru biroul sau sufrageria Dvs.",
                            ImageUrl = "/images/subcategory/articole-personalizate/ceasuri-personalizate.jpg",
                            Name = "Ceasuri Personalizate",
                            Url = "ceasuri-personalizate"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Puzzle-ul personalizat este ideal pentru un cadou unic de pentru aniversari, Craciun sau chiar pentru tine. O fotografie Puzzle este u mod popular si surprinzator de a trimite un mesaj frumos persoanei dragi. Puteti opta pentru puzzle cartonat drept-unghi sau in forma de inima. Trimiteti poza preferata pe adresa de e-mail: contact@drprint.ro iar noi vom realiza puzzle-ul Dvs. personalizat de cea mai inalta calitate!",
                            ImageUrl = "/images/subcategory/articole-personalizate/puzzle-personalizat.jpg",
                            Name = "Puzzle Personalizat",
                            Url = "puzzle-personalizat"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Profesionale si practice, personalizate Mouse pad-uri adăuga o nota personala la birou. Adaugati fotografii, logo-ul sau un mesaj pentru a crea un cadou distractiv sau daruiti-l clientilor ca si obiect promotional. Disponibile in forma rotunda, drept-unghiulara sau in forma de inima.",
                            ImageUrl = "/images/subcategory/articole-personalizate/mousepad-personalizat.jpg",
                            Name = "Mousepad-uri Personalizate",
                            Url = "mousepad-uri-personalizate"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Personalizam genti de umar de calitate superioara, de satin cu fermoar, diverse dimensiuni, pentru folosirea de zi cu zi sau pentru laptop.",
                            ImageUrl = "/images/subcategory/articole-personalizate/genti-personalizate.jpg",
                            Name = "Genti Personalizate",
                            Url = "genti-personalizate"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Jucarii de plus pentru copilul tau, personalizate cu poza si textul favorite, un cadou minunat cu ocazia Sarbatorilor de iarna. Puteti alege: ursuleti de plus, panda, ren de plus, ren de plus cu caciulita, iepuras.",
                            ImageUrl = "/images/subcategory/articole-personalizate/jucarii-de-plus-personalizate.jpg",
                            Name = "Jucarii De Plus Personalizate",
                            Url = "jucarii-de-plus-personalizate"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "Personalizam veste pentru activitati de constructii, drumuri etc sau prntru activitati sportive (veste departajare). ",
                            ImageUrl = "/images/subcategory/articole-personalizate/veste-reflectorizante-personalizate.jpg",
                            Name = "Veste Reflectorizante Personalizate",
                            Url = "veste-reflextorizante-personalizate"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Description = "Sort bucatarie personalizat cu poza sau textul favorite - acorda o nota profesinala restaurantului Dvs. sau reprezinta un cadou minunat pt mama, sotia sau bunica Dvs.",
                            ImageUrl = "/images/subcategory/articole-personalizate/sort-bucatarie-personalizat.jpg",
                            Name = "Sort Bucatarie Personalizat",
                            Url = "sort-bucatarie-personalizat"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Carnetele personalizate ideale pentru scoli, licee sau un cadou unic si practic pentru prieteni. ",
                            ImageUrl = "/images/subcategory/articole-personalizate/carnetele-personalizate.jpg",
                            Name = "Carnetele Personalizate Cu Insertie Foto",
                            Url = "carnetele-personalizate-cu-insertie-foto"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "Placi ardezie ( piatra naturala ) personalizate foto. Fiecare bucata un unicat. Calitate masiva. Va puteti decora sufrageria, biroul, sau face un cadou unic, deosebit.",
                            ImageUrl = "/images/subcategory/articole-personalizate/piatra-naturala-personalizata.jpg",
                            Name = "Placi Ardezie / Piatra Naturala Personalizate",
                            Url = "placi-ardezie-piatra-naturala-personalizate"
                        },
                        new
                        {
                            Id = 192,
                            CategoryId = 1,
                            Description = "Sacose textile personalizate cu poza sau textul favorite ideale pentru un cadou unic pentru persoanele dragi sau un mijloc de promovare pentru afacerea ta.",
                            ImageUrl = "/images/subcategory/articole-personalizate/sacose-personalizate.jpg",
                            Name = "Sacose Shopping Panza Personalizate",
                            Url = "sacose-shopping-panza-personalizate"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "Portofelele sunt unul dintre accesoriile cele mai importante in vita de zi cu zi. Confera-le personalitate! Personalizeaza-le cu poza favorita si fa-le cadou prietenilor sau foloseste-le ca obiecte promotionale pentru a-ti promova afacerea.",
                            ImageUrl = "/images/subcategory/articole-personalizate/portofele-personalizate.jpg",
                            Name = "Portofele Personalizate",
                            Url = "portofele-personalizate"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Description = "Halbe de bere personalizate cu poza, textul sau sigla dorita ideale pentru brandul restaurantului Dvs sau cadou pentru prieteni. ",
                            ImageUrl = "/images/subcategory/articole-personalizate/halbe-de-bere-personalizate.jpg",
                            Name = "Halbe De Bere Personalizate",
                            Url = "halbe-de-bere-personalizate"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Description = "Personalizam o gama variata de suporturi de pahare pe care le puteti darui prietenilor, va puteti brandui barul sau pe puteti darui ca obiecte promotionale pentru a va face cunoscuta afacerea. ",
                            ImageUrl = "/images/subcategory/articole-personalizate/suporturi-pahare-personalizate.jpg",
                            Name = "Suporturi Pahare Personalizate",
                            Url = "suporturi-pahare-personalizate"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            Description = "Note-book personalizat, coperta si fiecare pagina in parte cu datele preferate. Ideal pentru afacerea ta sau caiet personalizat pentru copilul tau.",
                            ImageUrl = "/images/subcategory/articole-personalizate/note-book-personalizat.jpg",
                            Name = "Note-book Personalizat",
                            Url = "note-book-personalizat"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            Description = "Tricouri haioase pentru ea, pt el sau pt cuplul vostru, un cadou deosebit pentru jumatatea ta sau prieteni pentru orice ocazie.",
                            ImageUrl = "/images/subcategory/articole-personalizate/tricouri-haioase.jpg",
                            Name = "Tricouri Haioase",
                            Url = "tricouri-haioase"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Description = "Bidoane sport cu capac personalizate cu imaginea favorita, ideale pt activitatile sportive, sala, biciclisti, calatorii montane sau ca mijloc de promovare.",
                            ImageUrl = "/images/subcategory/articole-personalizate/bidoane-personalizate.jpg",
                            Name = "Bidoane Sport Metalice Personalizate",
                            Url = "bidoane-sport-metalice-personalizate"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            Description = "",
                            ImageUrl = "/images/subcategory/articole-personalizate/brelocuri-personalizate.jpg",
                            Name = "Brelocuri Metalice Cu Insertie Foto",
                            Url = "brelocuri-metalice-cu-insertie-foto"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            Description = "Am aflat un secret! Mos Craciun ia cadourile personalizate de la DRPRINT.RO! Peantru Ea, pentru El, Mamici, Tatici si Bunici, toate le gasiti aici! Intra si tu si alege din multitudinea de cadouri: globuri foto, cani, jucarii de plus, penare, ornamente ceramice, fotografii si rame foto, magneti de frigider si multe altele.",
                            ImageUrl = "/images/subcategory/articole-personalizate/cadouri-personalizate.jpg",
                            Name = "Cadouri Personalizate",
                            Url = "cadouri-personalizate"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Description = "Prin cartea de vizita oamenii isi creeaza prima impresie, astfel ca aceasta trebuie sa puna in lumina cat mai pozitiv activitatea si profilul Dvs. Va oferim Carti de Vizita color printate pe carton special super-glossy. Realizam fonte excelente. Nu aveti un design care sa va reprezinte? Apeleti la specialistii nostri! Va punem la dispozitie o serie de modele si le personalizam cu detaliile Dvs. Cea mai mare partea a cartoanelor folosite provin din materie reciclata. Daca aveti o singura sansa de a va face o prima impresie, faceti una buna!",
                            ImageUrl = "/images/subcategory/print-digital/carti-de-vizita.jpg",
                            Name = "Carti De Vizita",
                            Url = "carti-de-vizita"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Description = "Etichete universale din hartie alba de inalta calitate, cu grad de alb mare si adeziv rezistent la temperaturi mari. Hartia din spatele autocolantului este de tip siliconic (80g/mp, 80 microni), iar hartia din fata este alba, mata ( 78g/mp, 74 microni).Adezivul este permanent. Etichetele sunt pretaiate fiind astfel usor de dezlipit de pe suportul din spate si usor de utilizat. ",
                            ImageUrl = "/images/subcategory/print-digital/etichete-autoadezive.jpg",
                            Name = "Etichete Autoadezive",
                            Url = "etichete-autoadezive"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Description = "Flyerele personalizate reprezinta un mod atragator de promovare a unui produs sau eveniment. Atrageti clienti noi sau informati cumparatorii cu privire la produse noi sau reduceri. Print full color fata verso pe hartie lucioasa de calitate superioara cu gramaje cuprinse intre 115-130 g/mp. Design modern si atragator pe care il puteti alege din modelele puse la dispozitie pe site si personalizate cu datele si logoul Dvs. de specialistii nostri pentru un impact vizual exceptioanal asupra viitorilor clienti. Capacitate mare de productie si termene reduse de executie si transport.",
                            ImageUrl = "/images/subcategory/print-digital/flyere.jpg",
                            Name = "Flyere",
                            Url = "flyere"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Description = "Pliantele personalizate reprezinta un mod atragator de promovare a unui produs sau eveniment. Atrageti clienti noi sau informati cumparatorii cu privire la produse noi sau reduceri. Print full color fata verso pe hartie lucioasa de calitate superioara cu gramaje cuprinse intre 115-130 g/mp. Design modern si atragator pe care il puteti alege din modelele puse la dispozitie pe site si personalizate cu datele si logoul Dvs. de specialistii nostri pentru un impact vizual exceptioanal asupra viitorilor clienti. Capacitate mare de productie si termene reduse de executie si transport.",
                            ImageUrl = "/images/subcategory/print-digital/pliante.jpg",
                            Name = "Pliante",
                            Url = "pliante"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Description = "Realizam invitatii pentru nunti, botezuri si alte evenimente speciale din viata Dvs. Personalizate cu textele favorite si printate pe cartoane speciale sau cu aplicatii Glitter, Emboss, stantate sau in relief, invitatiile speciele de la Dr Print va ajuta sa anuntati cele mai placute evenimente din viata Dvs. in cel mai elegant mod.",
                            ImageUrl = "/images/subcategory/print-digital/invitatii.jpg",
                            Name = "Invitatii",
                            Url = "invitatii"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            Description = "Asigurati-va ca partenerii de afaceri si clientii recunosc corespondenta de la compania dvs. dintr-o privire prin utilizarea plicurilor personalizate de afaceri. Adaugati logo-ul dvs. si adresa expeditorului. De asemenea puteti folosi plicurile personalizate pentru ocaziile speciale din viata Dvs, nunti, botezuri etc. Selectati plicuri personalizate intr-o varietate de dimensiuni pentru a satisface nevoile exacte ale companiei.",
                            ImageUrl = "/images/subcategory/print-digital/plicuri-personalizate.jpg",
                            Name = "Plicuri Personalizate",
                            Url = "plicuri-personalizate"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 2,
                            Description = "Printarea se face pe utilaje Konica Minolta si Canon noi. Realizam fonte, calitate exceptionala. Media de printare variaza intre 80 si 300 g/mp.",
                            ImageUrl = "/images/subcategory/print-digital/print-a4-a3.jpg",
                            Name = "Print A4 / A3",
                            Url = "print-a4-a3"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Description = "Primul pas catre realizarea unei noi afaceri este reprezentat de prezentarea informatiilor companiei dvs catre clienti. In mapele personalizate de inalta calitate puteti cuprinde intreaga informatie necesara. Acestea contin buzunare adanci pentru documente si CD-uri de prezentare si suport pentru cartile Dvs de vizita.",
                            ImageUrl = "/images/subcategory/print-digital/mape-de-prezentare.jpg",
                            Name = "Mape De Prezentare Si Notebook Personalizat",
                            Url = "mape-de-prezentare-si-notebook-personalizat"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 2,
                            Description = "Indosariati printurile Dvs. intr-un singur document eliminand astfel riscul de pierdere sau amestecarea paginilor. Un document indosaiat va fii mut mai usor de utilizat si de depozitat.Puteti indosaria documente, carti copiate, cursuri dar si portofolii de prezentare, cataloage, meniuri etc., spirala plastic sau metal, coperta plastic transparenta fata pentru protectia documentului si o nota de eleganta, coperta carton imitatie piele spate culoare neagra sau alba",
                            ImageUrl = "/images/subcategory/print-digital/servicii-indosariere.jpg",
                            Name = "Servicii Indosariere Documente",
                            Url = "servicii-indosariere-documente"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 2,
                            Description = "Serviciul nostru de scanare la cerere maximizeaza eficienta, accesibilitatea si securitatea si va salva compania dvs. de costul de recuperare a documentatiei pe suport de hartie. Folosind acest serviciu fantastic inseamna ca biroul dumneavoastra nu va mai fi ingreunata cu fisiere si documente ca tot ceea ce aveti nevoie este returnat in format digital putand fi securizat prin parola. Tot ce trebuie sa faceti este sa ne furnizati documentele si le veti avea pe ecran in cateva minute! Scanam documente si fotografii color la  o rezolutie ridicata (600 dpi)  in format PDF, JPG, TIFF, formate A4 sau A3. Viteza mare de scanare si posibilitatea de scanare paginilor multiple intr-un singur document PDF sau separate.",
                            ImageUrl = "/images/subcategory/print-digital/scanare-documente.jpg",
                            Name = "Scanare Documente",
                            Url = "scanare-documente"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 2,
                            Description = "Copiem documente alb-negru sau color pe utileje Konica Minolta noi avand conferind o calitate ridicata a serviciului si viteza mare de copiere atat fata cat si fata-verso. Realizam fonte. Copierea se realizeaza pe hartie standard 80 g/mp, dimensiuni A4 sau A3.",
                            ImageUrl = "/images/subcategory/print-digital/fotocopiere.jpg",
                            Name = "Fotocopiere",
                            Url = "fotocopiere"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 3,
                            Description = "Rame foto din plastic, sticla si lemn sau rame foto cu ceas - un decor elegant pentru casa, birou, restaurante etc. Alegeti din multitudinea de modele si dimensiuni prezentate in fiecare categorie.",
                            ImageUrl = "/images/subcategory/fotografii-si-rame/rame-foto.jpg",
                            Name = "Rame Foto",
                            Url = "rame-foto"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            Description = "Printam fotografii pe hartie foto glossy superioara, conferind fotografiilor dumeavostra claritate, vivacitate si rezistenta in timp. Puteti astfel sa va afisati cele mai frumoase amintiri in culori vii, sa faceti cadouri pentru persoanele dragi, marturii pentru nunti si botezuri etc. Dimensiuni standard: 9x13 cm, 10 x 15 cm, 13x18 cm, 15x21 cm, 210x297 cm (A4), 297x420 cm (A3). Puteti solicita si orice alta dimensiune in functie de nevoiele Dvs.",
                            ImageUrl = "/images/subcategory/fotografii-si-rame/fotografii-digitale.jpg",
                            Name = "Fotografii Digitale",
                            Url = "fotografii-digitale"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Description = "Va punem la dispozitie o gama larga de sisteme de afisaj pentru a va promova afacerea sau diferite evenimente: People Stopper, Roll-up, Rame Aluminiu Click.",
                            ImageUrl = "/images/subcategory/productie-publicitara/sisteme-de-afisaj.jpg",
                            Name = "Sisteme De Afisaj",
                            Url = "sisteme-de-afisaj"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            Description = "Autocolantul este baza productiei publicitare. Acesta poate fii taiat la cutter plotter, printat sau folosit ca atare. Ideal pentru decorarea vitrinelor, orare, etc. Pretul se calculeza in functie de dimensiune la 20 Euro mp.",
                            ImageUrl = "/images/subcategory/productie-publicitara/autocolant.jpg",
                            Name = "Autocolant",
                            Url = "autocolant"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Description = "Realizam bannere de orice dimensiuni. Acestea sunt printate pe utilaj Mutoch la 1440 dpi, Eco-Solvent. Se printeaza pe Frontlit, Backlit sau panza de steag. Cereti oferta de pret in functie de dimensiune.",
                            ImageUrl = "/images/subcategory/productie-publicitara/bannere.jpg",
                            Name = "Bannere",
                            Url = "bannere"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            Description = "Casete luminoase simpla fata sau dubla fata realizate cu profil de aluminiu, fata de styplex, colate cu print pe autocolant translucent si ranforsate cu cadru metalic. Pretul de lista este de 180euro/mp (acesta poate fluctua in functie de comanda).",
                            ImageUrl = "/images/subcategory/productie-publicitara/casete-luminoase.jpg",
                            Name = "Casete Luminoase",
                            Url = "casete-luminoase"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            Description = "Realizam inscriptionari auto pentru orice tip de autovehicul. Inscriptionarea se realizeaza cu autocolant taiat la cutter sau cu autocolant printat. Windows graphics ofera geamurilor o nuanta aparte, iar masina dumneavoastra se va bucura de un nou look. Pretul se realizeaza pentru fiecare lucrare in parte.",
                            ImageUrl = "/images/subcategory/productie-publicitara/inscriptionari-auto.jpg",
                            Name = "Inscriptionari Auto",
                            Url = "inscriptionari-auto"
                        });
                });

            modelBuilder.Entity("DrPrint.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DrPrint.Shared.Address", b =>
                {
                    b.HasOne("DrPrint.Shared.User", null)
                        .WithOne("Address")
                        .HasForeignKey("DrPrint.Shared.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DrPrint.Shared.OrderItem", b =>
                {
                    b.HasOne("DrPrint.Shared.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrPrint.Shared.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DrPrint.Shared.Product", b =>
                {
                    b.HasOne("DrPrint.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("DrPrint.Shared.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("DrPrint.Shared.SubCategory", b =>
                {
                    b.HasOne("DrPrint.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DrPrint.Shared.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DrPrint.Shared.User", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
